### ISSUE TITLE
react 0.14 cannot be used with jsx-test

### ISSUE THREAD

**Issue by jakepusateri** [yahoo/jsx-test#27]
https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html is out, but when trying to upgrade, npm throws 
`npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!`
due to the peerDependencies of "^0.13.0" in this package.

**Comment by 3den** [comment]
@jakepusateri I will to publish a new version of jsx-test ASAP, thanks for the notice.

**Comment by jakepusateri** [comment]
Any update on this? Is it more than updating the version to ">=0.13.0" ?

**Comment by 3den** [comment]
Seems like React deprecated the `TestUtils.SimulateNative` and I did not find a replacement for that yet. If you would like to send a PR that would be awesome.

**Comment by mridgway** [comment]
Any ideas on this yet @3den? We're blocked on internal upgrades due to this. Should dependents start migrating off of this package?

**Comment by pbeets** [comment]
Would like to know as well.

**Comment by 3den** [comment]
@mridgway @pbeets @jakepusateri sorry for the delay guys, I had been very busy lately but I will get this update done this weekend.

**Comment by 3den** [comment]
The update is above.
